/*

 MAIN_TILE_SET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 71

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Gameboy Color palette 0 */
#define MainTileSetCGBPal0c0 32767
#define MainTileSetCGBPal0c1 22197
#define MainTileSetCGBPal0c2 10570
#define MainTileSetCGBPal0c3 0

/* Gameboy Color palette 1 */
#define MainTileSetCGBPal1c0 32767
#define MainTileSetCGBPal1c1 480
#define MainTileSetCGBPal1c2 15360
#define MainTileSetCGBPal1c3 0

/* Gameboy Color palette 2 */
#define MainTileSetCGBPal2c0 32767
#define MainTileSetCGBPal2c1 31
#define MainTileSetCGBPal2c2 24
#define MainTileSetCGBPal2c3 18

/* Gameboy Color palette 3 */
#define MainTileSetCGBPal3c0 32767
#define MainTileSetCGBPal3c1 1023
#define MainTileSetCGBPal3c2 670
#define MainTileSetCGBPal3c3 330

/* Gameboy Color palette 4 */
#define MainTileSetCGBPal4c0 19475
#define MainTileSetCGBPal4c1 22756
#define MainTileSetCGBPal4c2 29873
#define MainTileSetCGBPal4c3 0

/* Gameboy Color palette 5 */
#define MainTileSetCGBPal5c0 13919
#define MainTileSetCGBPal5c1 12541
#define MainTileSetCGBPal5c2 14385
#define MainTileSetCGBPal5c3 0

/* Gameboy Color palette 6 */
#define MainTileSetCGBPal6c0 21374
#define MainTileSetCGBPal6c1 13809
#define MainTileSetCGBPal6c2 11996
#define MainTileSetCGBPal6c3 0

/* Gameboy Color palette 7 */
#define MainTileSetCGBPal7c0 32733
#define MainTileSetCGBPal7c1 23301
#define MainTileSetCGBPal7c2 12709
#define MainTileSetCGBPal7c3 0

/* End of MAIN_TILE_SET.H */
