/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SpritesBank 0

/* Super Gameboy palette 0 */
#define SpritesSGBPal0c0 6076
#define SpritesSGBPal0c1 8935
#define SpritesSGBPal0c2 6596
#define SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpritesSGBPal1c0 6076
#define SpritesSGBPal1c1 8935
#define SpritesSGBPal1c2 6596
#define SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpritesSGBPal2c0 6076
#define SpritesSGBPal2c1 8935
#define SpritesSGBPal2c2 6596
#define SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpritesSGBPal3c0 6076
#define SpritesSGBPal3c1 8935
#define SpritesSGBPal3c2 6596
#define SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpritesCGBPal0c0 32767
#define SpritesCGBPal0c1 22197
#define SpritesCGBPal0c2 10570
#define SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SpritesCGBPal1c0 32767
#define SpritesCGBPal1c1 480
#define SpritesCGBPal1c2 15360
#define SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SpritesCGBPal2c0 32767
#define SpritesCGBPal2c1 31
#define SpritesCGBPal2c2 24
#define SpritesCGBPal2c3 18

/* Gameboy Color palette 3 */
#define SpritesCGBPal3c0 32767
#define SpritesCGBPal3c1 1023
#define SpritesCGBPal3c2 670
#define SpritesCGBPal3c3 330

/* Gameboy Color palette 4 */
#define SpritesCGBPal4c0 32767
#define SpritesCGBPal4c1 1023
#define SpritesCGBPal4c2 670
#define SpritesCGBPal4c3 24

/* Gameboy Color palette 5 */
#define SpritesCGBPal5c0 32767
#define SpritesCGBPal5c1 25368
#define SpritesCGBPal5c2 19026
#define SpritesCGBPal5c3 12684

/* Gameboy Color palette 6 */
#define SpritesCGBPal6c0 32767
#define SpritesCGBPal6c1 25368
#define SpritesCGBPal6c2 19026
#define SpritesCGBPal6c3 12684

/* Gameboy Color palette 7 */
#define SpritesCGBPal7c0 32767
#define SpritesCGBPal7c1 25368
#define SpritesCGBPal7c2 19026
#define SpritesCGBPal7c3 12684

/* End of SPRITES.H */