/*

 WORLD_TILE_SET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 78

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define WorldTileSetBank 0

/* Super Gameboy palette 0 */
#define WorldTileSetSGBPal0c0 6076
#define WorldTileSetSGBPal0c1 8935
#define WorldTileSetSGBPal0c2 6596
#define WorldTileSetSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define WorldTileSetSGBPal1c0 6076
#define WorldTileSetSGBPal1c1 8935
#define WorldTileSetSGBPal1c2 6596
#define WorldTileSetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define WorldTileSetSGBPal2c0 6076
#define WorldTileSetSGBPal2c1 8935
#define WorldTileSetSGBPal2c2 6596
#define WorldTileSetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define WorldTileSetSGBPal3c0 6076
#define WorldTileSetSGBPal3c1 8935
#define WorldTileSetSGBPal3c2 6596
#define WorldTileSetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define WorldTileSetCGBPal0c0 32767
#define WorldTileSetCGBPal0c1 22197
#define WorldTileSetCGBPal0c2 10570
#define WorldTileSetCGBPal0c3 0

/* Gameboy Color palette 1 */
#define WorldTileSetCGBPal1c0 32767
#define WorldTileSetCGBPal1c1 480
#define WorldTileSetCGBPal1c2 15360
#define WorldTileSetCGBPal1c3 0

/* Gameboy Color palette 2 */
#define WorldTileSetCGBPal2c0 32767
#define WorldTileSetCGBPal2c1 31
#define WorldTileSetCGBPal2c2 24
#define WorldTileSetCGBPal2c3 18

/* Gameboy Color palette 3 */
#define WorldTileSetCGBPal3c0 32767
#define WorldTileSetCGBPal3c1 1023
#define WorldTileSetCGBPal3c2 670
#define WorldTileSetCGBPal3c3 330

/* Gameboy Color palette 4 */
#define WorldTileSetCGBPal4c0 19475
#define WorldTileSetCGBPal4c1 22756
#define WorldTileSetCGBPal4c2 29873
#define WorldTileSetCGBPal4c3 0

/* Gameboy Color palette 5 */
#define WorldTileSetCGBPal5c0 13919
#define WorldTileSetCGBPal5c1 12541
#define WorldTileSetCGBPal5c2 14385
#define WorldTileSetCGBPal5c3 0

/* Gameboy Color palette 6 */
#define WorldTileSetCGBPal6c0 21374
#define WorldTileSetCGBPal6c1 13809
#define WorldTileSetCGBPal6c2 11996
#define WorldTileSetCGBPal6c3 0

/* Gameboy Color palette 7 */
#define WorldTileSetCGBPal7c0 32733
#define WorldTileSetCGBPal7c1 23301
#define WorldTileSetCGBPal7c2 12709
#define WorldTileSetCGBPal7c3 0
/* CGBpalette entries. */
//extern unsigned char WorldTileSetCGB[];
/* Start of tile array. */
//extern unsigned char WorldTileSet[];

/* End of WORLD_TILE_SET.H */
